# Generated by Django 2.2.7 on 2020-09-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanoBasicAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField(verbose_name=3)),
                ('Active', models.PositiveIntegerField(verbose_name=3)),
                ('Recovery', models.PositiveIntegerField(verbose_name=3)),
                ('HitAdv', models.PositiveIntegerField(verbose_name=3)),
                ('BlockAdv', models.SmallIntegerField(verbose_name=10)),
                ('FBlockAdv', models.SmallIntegerField(verbose_name=10)),
            ],
        ),
    ]
