# Generated by Django 2.2.7 on 2020-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanobasicattacks',
            name='Startup',
            field=models.PositiveIntegerField(),
        ),
    ]
