# Generated by Django 2.2.7 on 2020-09-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0002_auto_20200901_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadeBasicAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JadeSpecialAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JadeStringAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanoSpecialMoveAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanoStringAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NightwolfBasicAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NightwolfSpecialAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NightwolfStringAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubZeroBasicAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubZeroSpecialAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubZeroStringAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='kanobasicattacks',
            name='Active',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kanobasicattacks',
            name='BlockAdv',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='kanobasicattacks',
            name='FBlockAdv',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='kanobasicattacks',
            name='HitAdv',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kanobasicattacks',
            name='Recovery',
            field=models.PositiveIntegerField(),
        ),
    ]
