# Generated by Django 2.2.7 on 2020-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0003_auto_20200904_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanoSpecialMoveAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='JadeBasicAttacks',
            new_name='JadeBasicAttack',
        ),
        migrations.RenameModel(
            old_name='JadeSpecialAttacks',
            new_name='JadeSpecialAttack',
        ),
        migrations.RenameModel(
            old_name='JadeStringAttacks',
            new_name='JadeStringAttack',
        ),
        migrations.RenameModel(
            old_name='KanoBasicAttacks',
            new_name='KanoBasicAttack',
        ),
        migrations.RenameModel(
            old_name='KanoStringAttacks',
            new_name='KanoStringAttack',
        ),
        migrations.RenameModel(
            old_name='NightwolfBasicAttacks',
            new_name='NightwolfBasicAttack',
        ),
        migrations.RenameModel(
            old_name='NightwolfSpecialAttacks',
            new_name='NightwolfSpecialAttack',
        ),
        migrations.RenameModel(
            old_name='NightwolfStringAttacks',
            new_name='NightwolfStringAttack',
        ),
        migrations.RenameModel(
            old_name='SubZeroBasicAttacks',
            new_name='SubZeroBasicAttack',
        ),
        migrations.RenameModel(
            old_name='SubZeroSpecialAttacks',
            new_name='SubZeroSpecialAttack',
        ),
        migrations.RenameModel(
            old_name='SubZeroStringAttacks',
            new_name='SubZeroStringAttack',
        ),
        migrations.DeleteModel(
            name='KanoSpecialMoveAttacks',
        ),
    ]
