# Generated by Django 2.2.7 on 2020-09-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0004_auto_20200904_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KanoSpecialMoveAttack',
        ),
    ]
