# Generated by Django 2.2.7 on 2020-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0005_delete_kanospecialmoveattack'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanoSpecialAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.PositiveIntegerField()),
                ('Recovery', models.PositiveIntegerField()),
                ('HitAdv', models.PositiveIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
    ]
