# Generated by Django 2.2.7 on 2020-09-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0007_auto_20200910_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KanoBasicAttack',
            new_name='KanoRipperBasicAttack',
        ),
    ]
