# Generated by Django 2.2.7 on 2020-09-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0008_auto_20200919_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KanoRipperBasicAttack',
            new_name='KanoBasicAttack',
        ),
    ]
