# Generated by Django 2.2.7 on 2020-09-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0012_auto_20200924_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightwolfbasicattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
