# Generated by Django 2.2.7 on 2020-09-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0013_nightwolfbasicattack_movetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanobasicattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='kanodirtbagattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='kanoripperattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='kanospecialattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='kanostringattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
