# Generated by Django 2.2.7 on 2020-09-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0014_auto_20200924_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightwolfAncestralAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('MoveType', models.CharField(default='None', max_length=50)),
                ('Buttons', models.CharField(default='N/A', max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.SmallIntegerField()),
                ('Recovery', models.SmallIntegerField()),
                ('HitAdv', models.SmallIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NightwolfMatokaAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('MoveType', models.CharField(default='None', max_length=50)),
                ('Buttons', models.CharField(default='N/A', max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.SmallIntegerField()),
                ('Recovery', models.SmallIntegerField()),
                ('HitAdv', models.SmallIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='jadebasicattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='jadespecialattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='jadestringattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='nightwolfspecialattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='nightwolfstringattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='subzerobasicattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='subzerospecialattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='subzerostringattack',
            name='MoveType',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
