# Generated by Django 2.2.7 on 2020-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kombat', '0015_auto_20200924_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadeEmeraldAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('MoveType', models.CharField(default='None', max_length=50)),
                ('Buttons', models.CharField(default='N/A', max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.SmallIntegerField()),
                ('Recovery', models.SmallIntegerField()),
                ('HitAdv', models.SmallIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JadeJadedAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('MoveType', models.CharField(default='None', max_length=50)),
                ('Buttons', models.CharField(default='N/A', max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.SmallIntegerField()),
                ('Recovery', models.SmallIntegerField()),
                ('HitAdv', models.SmallIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubZeroDeadofWinterAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('MoveType', models.CharField(default='None', max_length=50)),
                ('Buttons', models.CharField(default='N/A', max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.SmallIntegerField()),
                ('Recovery', models.SmallIntegerField()),
                ('HitAdv', models.SmallIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubZeroThinIceAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Move', models.CharField(max_length=50)),
                ('MoveType', models.CharField(default='None', max_length=50)),
                ('Buttons', models.CharField(default='N/A', max_length=50)),
                ('Startup', models.PositiveIntegerField()),
                ('Active', models.SmallIntegerField()),
                ('Recovery', models.SmallIntegerField()),
                ('HitAdv', models.SmallIntegerField()),
                ('BlockAdv', models.SmallIntegerField()),
                ('FBlockAdv', models.SmallIntegerField()),
            ],
        ),
    ]
